default:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  host: db
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>

development:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  host: db
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  database: messagecard_development

test:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  host: db
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  database: messagecard_test

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  host: db
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  database: messagecard_production