services:
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  backend:
    build:
      context: ./backend
      args:
        WORKDIR: ${WORKDIR}
    volumes:
      - "./backend:/app"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: ${WORKDIR}
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    depends_on:
      - backend